-- Business services for the hybrid topology page (topo_tree.php).
-- A service (Email, ERP, …) leans on topology nodes (devices, or groups =
-- all their devices) and on other services. Its status is the worst severity
-- found anywhere in its dependency tree, so a dead switch degrades every
-- service above it — the page walks that tree to show the root cause.
--
-- Run as postgres, then ownership is handed to the frontend role (zabbix)
-- at the bottom — the UI connects as zabbix and needs full DML rights.

CREATE TABLE IF NOT EXISTS topo_service (
	topo_serviceid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name           varchar(255) NOT NULL DEFAULT '',
	createdat      timestamptz NOT NULL DEFAULT now()
);

-- One dependency edge: exactly one of dep_serviceid / nodeid is set.
-- NULLS NOT DISTINCT (PostgreSQL 15+) makes the unique index catch
-- duplicates even though one of the columns is always NULL.
CREATE TABLE IF NOT EXISTS topo_service_dep (
	serviceid     bigint NOT NULL REFERENCES topo_service(topo_serviceid) ON DELETE CASCADE,
	dep_serviceid bigint REFERENCES topo_service(topo_serviceid) ON DELETE CASCADE,
	nodeid        bigint REFERENCES topo_node(topo_nodeid) ON DELETE CASCADE,
	UNIQUE NULLS NOT DISTINCT (serviceid, dep_serviceid, nodeid)
);

ALTER TABLE topo_service OWNER TO zabbix;
ALTER TABLE topo_service_dep OWNER TO zabbix;
