-- Network flows for the hybrid topology page (topo_tree.php).
-- A flow is a named one-way path: an ordered list of topology nodes the
-- packets visit. Enabled flows are drawn with directional arrows, per-node
-- sequence numbers and a running packet on the canvas.
--
-- Run as postgres, then ownership is handed to the frontend role (zabbix)
-- at the bottom — the UI connects as zabbix and needs full DML rights.

CREATE TABLE IF NOT EXISTS topo_flow (
	topo_flowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name        varchar(128) NOT NULL DEFAULT '',
	enabled     integer NOT NULL DEFAULT 1,
	ports       varchar(64) NOT NULL DEFAULT '',
	qos         varchar(64) NOT NULL DEFAULT '',
	createdat   timestamptz NOT NULL DEFAULT now()
);

-- seq is 0-based position along the path; ON DELETE CASCADE keeps hops in
-- sync with topo_node deletions (flows left with <2 hops are pruned by PHP).
CREATE TABLE IF NOT EXISTS topo_flow_hop (
	topo_flowid bigint NOT NULL REFERENCES topo_flow(topo_flowid) ON DELETE CASCADE,
	seq         integer NOT NULL,
	nodeid      bigint NOT NULL REFERENCES topo_node(topo_nodeid) ON DELETE CASCADE,
	PRIMARY KEY (topo_flowid, seq)
);

ALTER TABLE topo_flow OWNER TO zabbix;
ALTER TABLE topo_flow_hop OWNER TO zabbix;
